# Generated by Django 3.1.2 on 2020-10-15 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crashupload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crashdumpmodel',
            name='clientHostName',
        ),
        migrations.RemoveField(
            model_name='crashdumpmodel',
            name='clientUserName',
        ),
        migrations.RemoveField(
            model_name='crashdumpmodel',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='crashdumpmodel',
            name='crashHostName',
            field=models.CharField(help_text='full qualified host name of the crash application', max_length=256, null=True, verbose_name='Crash FQDN'),
        ),
        migrations.AddField(
            model_name='crashdumpmodel',
            name='crashUserName',
            field=models.CharField(help_text='username of the crash application', max_length=256, null=True, verbose_name='Crash user'),
        ),
        migrations.AddField(
            model_name='crashdumpmodel',
            name='crashtimestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Crash Timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crashdumpmodel',
            name='productCodeName',
            field=models.CharField(default=django.utils.timezone.now, help_text='code name of the product', max_length=256, verbose_name='Product code name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crashdumpmodel',
            name='reportHostName',
            field=models.CharField(help_text='full qualified host name of the reporter', max_length=256, null=True, verbose_name='Report FQDN'),
        ),
        migrations.AddField(
            model_name='crashdumpmodel',
            name='reportUserName',
            field=models.CharField(help_text='username of the reporter', max_length=256, null=True, verbose_name='Report user'),
        ),
        migrations.AddField(
            model_name='crashdumpmodel',
            name='reporttimestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Report Timestamp'),
            preserve_default=False,
        ),
    ]
