# Generated by Django 3.1.2 on 2020-10-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashupload', '0002_auto_20201015_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashdumpmodel',
            name='cpuType',
            field=models.IntegerField(choices=[(-1, 'Unknown'), (0, 'x86'), (1, 'MIPS'), (2, 'Alpha'), (3, 'PowerPC'), (4, 'SHX'), (5, 'ARM'), (6, 'IA64'), (7, 'Alpha64'), (8, 'MSIL'), (9, 'AMD64'), (10, 'x64 Win64'), (11, 'SPARC'), (12, 'PowerPC 64'), (13, 'ARM64')], default=-1, help_text='CPU type', verbose_name='CPU type'),
        ),
    ]
