# Generated by Django 4.0.3 on 2022-04-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashupload', '0003_crashdumpmodel_cputype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashdumpattachment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crashdumplink',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crashdumpmodel',
            name='buildType',
            field=models.CharField(choices=[('DEBUG', 'DEBUG'), ('RELWITHDEBINFO', 'RELWITHDEBINFO'), ('RELEASE', 'RELEASE'), ('MINSIZEREL', 'MINSIZEREL')], default='RELEASE', help_text='build type', max_length=16, verbose_name='Build type'),
        ),
        migrations.AlterField(
            model_name='crashdumpmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='crashdumpmodel',
            name='productCodeName',
            field=models.CharField(help_text='code name of the product', max_length=256, verbose_name='Code name'),
        ),
        migrations.AlterField(
            model_name='crashdumpmodel',
            name='productTargetVersion',
            field=models.CharField(help_text='target version of the product', max_length=24, verbose_name='Target version'),
        ),
        migrations.AlterField(
            model_name='crashdumpstate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
