# Generated by Django 4.0.3 on 2022-04-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashupload', '0004_alter_crashdumpattachment_id_alter_crashdumplink_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashDumpProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project name', max_length=32, verbose_name='Name')),
                ('description', models.CharField(help_text='description of the project', max_length=256, verbose_name='Description')),
                ('url', models.CharField(default=None, help_text='URL for the Project page', max_length=256, null=True, verbose_name='Url')),
                ('issueTrackerType', models.CharField(choices=[(None, 'None'), ('GitLab', 'GitLab')], default=None, help_text='Issue Tracker', max_length=16, null=True, verbose_name='Issue Tracker')),
                ('issueTrackerUrl', models.CharField(default=None, help_text='URL to the issue tracker', max_length=256, null=True, verbose_name='Issue Tracker Url')),
                ('issueTrackerToken', models.CharField(default=None, help_text='Token to access the issue tracker', max_length=256, null=True, verbose_name='Issue Tracker Token')),
                ('codename', models.CharField(default=None, help_text='Code name of the project for crash matching', max_length=256, verbose_name='Code name')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterField(
            model_name='crashdumpstate',
            name='description',
            field=models.CharField(help_text='description of the state', max_length=256, verbose_name='Description'),
        ),
    ]
