# Generated by Django 4.0.3 on 2022-04-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashupload', '0004_alter_crashdumpattachment_id_alter_crashdumplink_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrashDumpProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Project name', max_length=32, verbose_name='Name')),
                ('description', models.CharField(help_text='description of the attachment', max_length=256, verbose_name='Description')),
                ('issueTrackerType', models.CharField(choices=[(None, 'None'), ('GitLab', 'GitLab')], default=None, help_text='Issue Tracker', max_length=16, verbose_name='Issue Tracker')),
                ('issueTrackerUrl', models.CharField(default=None, help_text='URL to the issue tracker', max_length=256, verbose_name='Issue Tracker Url')),
                ('issueTrackerToken', models.CharField(default=None, help_text='Token to access the issue tracker', max_length=256, verbose_name='Issue Tracker Token')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
