# Generated by Django 4.0.3 on 2022-04-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crashupload', '0005_crashdumpproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='crashdumpproject',
            name='codename',
            field=models.CharField(default=None, help_text='Code name of the project for crash matching', max_length=256, verbose_name='Code name'),
        ),
        migrations.AlterField(
            model_name='crashdumpproject',
            name='description',
            field=models.CharField(help_text='description of the project', max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='crashdumpstate',
            name='description',
            field=models.CharField(help_text='description of the state', max_length=256, verbose_name='Description'),
        ),
    ]
